### ISSUE TITLE
1st page of candidate list cannot be display completely on screen edge

### ISSUE THREAD

**Issue by benny1hk** [Cangjians/ibus-cangjie#93] opened 2019-07-17 12:41 UTC
I am using ibus-quick on 
Ubuntu 18.04.2 LTS
Gnome 3.28.2

You will see when I type at the bottom of the screen, the first page of the candidate will be display out of the screen, but then if we go to next page, the box can be flip upward to display completely. So I guess it only happen when the box create.

![1](https://user-images.githubusercontent.com/5972312/61375636-f1cebd80-a8d1-11e9-8e76-388c99d8f0cb.jpg)
![2](https://user-images.githubusercontent.com/5972312/61375641-f5fadb00-a8d1-11e9-85e9-5cab6ac03ba8.jpg)

**Comment by bochecha** [comment] 2019-07-17 13:00
We don't display the candidate popup, GNOME Shell does, so this would be their bug.

However I can't reproduce the bug here on GNOME 3.32, so it might have already been fixed, which means you need to talk to your distribution instead.

Since this isn't our bug and there is nothing we can do about it, I'm going to close this.

**Closed by bochecha** 2019-07-17 13:00 UTC

**Comment by yookoala** [comment] 2019-07-17 14:36
I'm still on GNOME 3.28. And I can reproduce the issue.

Will try to get a GNOME 3.32 to test.

**Comment by yookoala** [comment] 2019-07-17 15:05
Also, ibus-tables (with ibus-tables-quick) does not have the same issue.

**Comment by bochecha** [comment] 2019-07-17 15:34
> Also, ibus-tables (with ibus-tables-quick) does not have the same issue.

Most likely the return of the preedit bug. Still, GNOME Shell draws the candidate popup, not us. We really can't do anything about this here.
