### ISSUE TITLE
Running ibus-setup-cangjie will crash (since 2018)

### ISSUE THREAD

**Issue by hosiet** [Cangjians/ibus-cangjie#96] opened 2019-12-17 19:28 UTC
This is a regression introduced in https://github.com/Cangjians/ibus-cangjie/commit/6b46d4c6ef043a631b03b359ee4882b05d7d08a8 .

Downstream Debian Bug: https://bugs.debian.org/946500

https://github.com/Cangjians/ibus-cangjie/blob/c96a3ac187e90b735c85e8cbc0ef57e2ae0435b9/src/setup.py#L21-L25

This is really wrong. Current Linux distributions only provides Gio and GLib of version 2.0, not 3.0. This typo will make `ibus-setup-cangjie` crash every time. I believe the fix would be trivial by replacing "3.0" for Gio and GLib with "2.0".

**Comment by bochecha** [comment] 2019-12-17 22:19
Yes, we know: https://github.com/Cangjians/ibus-cangjie/issues/94#issuecomment-528893770

Do note that this commit has never been released, so Debian shouldn't have pulled it in their package.

I'm going to close this as a duplicate of the other issue.

**Closed by bochecha** 2019-12-17 22:19 UTC
Labels: duplicate

**Comment by hosiet** [comment] 2019-12-17 22:20
Thanks. I guess I will fix it from Debian's side (any thus in Ubuntu later).

**Comment by bochecha** [comment] 2019-12-17 22:21
> Thanks. I guess I will fix it from Debian's side (any thus in Ubuntu later).

The fix for distros would really be to stick to stable releases, instead of packaging whatever is in master.

In any case, if you write a patch, I'm happy to receive a pull request.

**Comment by bochecha** [comment] 2019-12-18 16:56
@hosiet I'm still curious why Debian would be impacted though, does Debian package ibus-cangjie master? :confused:

**Comment by hosiet** [comment] 2019-12-18 17:01
That's kind of my fault since I cherry clicked several commit to suppress warnings but did not tested patches thoroughly :-/

Will surely be more cautious, especially when Ubuntu 20.04 LTS is around the corner (and the ibus-cangjie in Debian will be part of this LTS release).
